groups:
  - name: api
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.05
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "High error rate on {{ $labels.route }}"
          description: "The error rate for {{ $labels.route }} is above 5% for the last 10 minutes."

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket[5m])) by (le, method, route)) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time on {{ $labels.route }}"
          description: "The 95th percentile response time for {{ $labels.route }} is above 500ms for the last 10 minutes."

      - alert: ServiceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service down: {{ $labels.instance }}"
          description: "The service {{ $labels.instance }} has been down for more than 5 minutes."